ingestor/urls.py
from django.urls import path, include
from . import views

app_name = 'ingestor'

urlpatterns = [
    path('logentries/', views.LogEntryCreateView.as_view(), name='logentry_create'),
    path('test/', views.test_view, name='test_view'),
    path('sqs_consumer/', views.SQSConsumerView.as_view(), name='sqs_consumer'),
    path('search_logs/', views.search_logs, name='search_logs'),
]

logIngestor/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "logIngestor"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ing/', include('ingestor.urls'))
]

ingestor/models.py
from django.db import models


class LogEntry(models.Model):
    level = models.CharField(max_length=255)
    message = models.TextField()
    resourceId = models.CharField(max_length=255)
    timestamp = models.DateTimeField()
    traceId = models.CharField(max_length=255)
    spanId = models.CharField(max_length=255)
    commit = models.CharField(max_length=255)
    parentResourceId = models.CharField(max_length=255, blank=True, null=True)
    metadata = models.JSONField()

    def __str__(self):
        return f"Level: {self.level} \n Message: {self.message} \n Timestamp: {self.timestamp} \n TraceID: {self.traceId} \n Metadata: {self.metadata}"


'''

CREATE TABLE IF NOT EXISTS public.logs
(
    level character varying(255) COLLATE pg_catalog."default",
    message character varying(255) COLLATE pg_catalog."default",
    resourceid character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    traceid character varying(255) COLLATE pg_catalog."default",
    spanid character varying(255) COLLATE pg_catalog."default",
    commit character varying(255) COLLATE pg_catalog."default",
    parentresourceid character varying(255) COLLATE pg_catalog."default",
    metadata_parentresourceid character varying(255) COLLATE pg_catalog."default"
)

'''

ingestor/views.py
import json
import requests
from django.utils import timezone
from django.shortcuts import render, HttpResponse
from django.views import View
from rest_framework import generics
from .models import LogEntry
from .serializers import LogEntrySerializer
from dotenv import load_dotenv
import os
import psycopg2
import boto3
import threading
import time
from elasticsearch import Elasticsearch
from datetime import datetime


load_dotenv()

access_key = os.getenv('AWS_ACCESS_KEY')
secret_access_key = os.getenv('AWS_SECRET_KEY')
elasticsearch_url = "http://elasticsearch:9200/logs/_doc"

db_params = {
    'dbname': 'logingestor',
    'user': 'admin',
    'password': 'patil9922',
    'host': 'localhost',
    'port': '5432',
}

def test_view(request):
    # s3 = boto3.resource('s3')
    # for bucket in s3.buckets.all():
    #     print('bucket.name', bucket.name)
    print('keys', access_key, secret_access_key)
    return HttpResponse("Hello, this is the 'test' view!")


class LogEntryCreateView(generics.ListCreateAPIView):
    queryset = LogEntry.objects.all()
    serializer_class = LogEntrySerializer

    class_data = []

    def perform_create(self, serializer):
        instance = serializer.save()
        timestamp_str = timezone.localtime(instance.timestamp).isoformat()
        message_data = {
            "level": instance.level,
            "message": instance.message,
            "resourceId": instance.resourceId,
            "timestamp": timestamp_str,
            "traceId": instance.traceId,
            "spanId": instance.spanId,
            "commit": instance.commit,
            "metadata-parentResourceId": instance.metadata['parentResourceId']
        }
        # print('instance', instance)
        # print('message_data', message_data)
        # access_key = os.getenv('AWS_ACCESS_KEY')
        # secret_key = os.getenv('AWS_SECRET_KEY')
        # console_password = os.getenv('CONSOLE_PASSWORD')
        sqs_queue_url = os.getenv('SQS_URL')
        # print('secret_key', secret_key)
        client = boto3.client('sqs', aws_access_key_id=access_key, aws_secret_access_key=secret_access_key, region_name="eu-north-1")

        response = client.send_message(
            QueueUrl=sqs_queue_url,
            MessageBody=json.dumps(message_data)
        )

        print("Message sent to SQS. Response:", response)

        self.__class__.class_data.append(instance)


class SQSConsumerView(View):
    def get(self, request, *args, **kwargs):
        # Start a background thread to consume messages
        background_thread = threading.Thread(target=self.consume_messages)
        background_thread.start()

        return HttpResponse("Background thread started for SQS consumer.")

    def consume_messages(self):
        try:
            while True:
                print("Fetching and processing SQS messages...")

                client = boto3.client('sqs', aws_access_key_id=access_key, aws_secret_access_key=secret_access_key, region_name="eu-north-1")
                sqs_queue_url = os.getenv('SQS_URL')
                response = client.receive_message(
                    QueueUrl=sqs_queue_url,
                    AttributeNames=['All'],
                    MessageAttributeNames=['All'],
                    MaxNumberOfMessages=10,
                    VisibilityTimeout=0,
                    WaitTimeSeconds=5
                )

                messages = response.get('Messages', [])
                if messages:
                    for message in messages:
                        # Process the message
                        json_data = json.loads(message["Body"])
                        self.process_message(json_data)
                        print("message from sqs : ", json_data)
                        # Delete the processed message
                        receipt_handle = message['ReceiptHandle']
                        client.delete_message(
                            QueueUrl=sqs_queue_url,
                            ReceiptHandle=receipt_handle
                        )
                time.sleep(15)
        except Exception as e:
            print(f"Error processing messages: {e}")

    def process_message(self, message):
        # push to elastic search

        json_data = json.dumps(message)

        headers = {
            "Content-Type": "application/json",
        }

        response = requests.post(elasticsearch_url, data=json_data, headers=headers)

        if response.status_code == 201:
            print("Data successfully indexed in Elasticsearch.")
        else:
            print(f"Failed to index data. Status code: {response.status_code}, Response: {response.text}")

        # push to postgres

        connection = psycopg2.connect(**db_params)
        cursor = connection.cursor()

        insert_query = """
        INSERT INTO logs (level, message, resourceId, created_at, traceId, spanId, commit, metadata_parentResourceId)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s);
        """

        cursor.execute(insert_query, (message["level"], message["message"], message["resourceId"], message["timestamp"], message["traceId"], message["spanId"], message["commit"], message["metadata-parentResourceId"]))
        connection.commit()

        cursor.close()
        connection.close()


def search_logs(request):
    if request.method == 'GET':
        return render(request, 'index.html')
    else:
        level = request.POST.get('level')
        message = request.POST.get('message')
        resourceId = request.POST.get('resourceId')
        timestamp_start = request.POST.get('timestamp_start')
        timestamp_end = request.POST.get('timestamp_end')
        traceId = request.POST.get('traceId')
        spanId = request.POST.get('spanId')
        commit = request.POST.get('commit')
        metadata_parentResourceId = request.POST.get('metadata_parentResourceId')

        must = []

        if level != '':
            must.append({"match": {"level": level}})
        if resourceId != '':
            must.append({"match": {"resourceId": resourceId}})
        if traceId != '':
            must.append({"match": {"traceId": traceId}})
        if spanId != '':
            must.append({"match": {"spanId": spanId}})
        if commit != '':
            must.append({"match": {"commit": commit}})
        if metadata_parentResourceId != '':
            must.append({"match": {"metadata_parentResourceId": metadata_parentResourceId}})

        # print('must', must)
        # print(type(must[0]))

        if len(level) + len(resourceId) + len(traceId) + len(spanId) + len(commit) + len(metadata_parentResourceId) > 0:
            search_query = {
                "query": {
                    "bool": {
                        "must": must
                    }
                }
            }
        elif message != '':
            search_query = {
                "query": {
                    "match": {
                        "message": {
                            "query": message,
                            "operator": "and"  # or "phrase"
                        }
                    }
                }
            }
        elif len(timestamp_start) + len(timestamp_end) > 0:
            timestamp_start += ":00"
            timestamp_end += ":00"

            # Convert to ISO 8601 format
            iso_format1 = datetime.fromisoformat(timestamp_start).isoformat()
            iso_format2 = datetime.fromisoformat(timestamp_end).isoformat()
            # return render(request, 'index.html')
            search_query = {
                "query": {
                    "range": {
                        "timestamp": {
                            "gte": iso_format1,
                            "lte": iso_format2,
                            "format": "strict_date_optional_time"
                        }
                    }
                }
            }

        es = Elasticsearch(['http://elasticsearch:9200'])
        result = es.search(index='logs', body=search_query)
        # print('result', result)
        hits = result['hits']['hits']
        logs = []
        for hit in hits:
            source_data = hit['_source']
            logs.append(source_data)
            # print('source_data', source_data)
        print('logs', logs)
        context = {
            'logs': logs,
        }

        return render(request, 'index.html', context)

ingestor/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log Search</title>
</head>
<body>

    <h1>Log Search</h1>

    <form method="post" action="{% url 'ingestor:search_logs' %}">
        <!-- Level -->
        {% csrf_token %}
        <label for="id_level">Level:</label>
        <input type="text" name="level" id="id_level">

        <!-- Message -->
        <label for="id_message">Message:</label>
        <input type="text" name="message" id="id_message">

        <!-- Resource ID -->
        <label for="id_resourceId">Resource ID:</label>
        <input type="text" name="resourceId" id="id_resourceId">

        <!-- Timestamp (Start) -->
        <label for="id_timestamp_start">Timestamp (Start):</label>
        <input type="datetime-local" name="timestamp_start" id="id_timestamp_start">

        <!-- Timestamp (End) -->
        <label for="id_timestamp_end">Timestamp (End):</label>
        <input type="datetime-local" name="timestamp_end" id="id_timestamp_end">

        <!-- Trace ID -->
        <label for="id_traceId">Trace ID:</label>
        <input type="text" name="traceId" id="id_traceId">

        <!-- Span ID -->
        <label for="id_spanId">Span ID:</label>
        <input type="text" name="spanId" id="id_spanId">

        <!-- Commit -->
        <label for="id_commit">Commit:</label>
        <input type="text" name="commit" id="id_commit">

        <!-- Parent Resource ID -->
        <label for="id_metadata_parentResourceId">Parent Resource ID:</label>
        <input type="text" name="metadata_parentResourceId" id="id_metadata_parentResourceId">

        <br>

        <input type="submit" value="Search">
    </form>

    {% if logs %}
    <h2>Search Results:</h2>
    <ul>
        {% for log in logs %}
            <li>
                <strong>Level:</strong> {{ log.level }}<br>
                <strong>Message:</strong> {{ log.message }}<br>
                <strong>Resource ID:</strong> {{ log.resourceId }}<br>
                <strong>Timestamp:</strong> {{ log.timestamp }}<br>
                <strong>Trace ID:</strong> {{ log.traceId }}<br>
                <strong>Span ID:</strong> {{ log.spanId }}<br>
                <strong>Commit:</strong> {{ log.commit }}<br>
                <strong>Parent Resource ID:</strong> {{ log.metadata.parentResourceId }}
            </li>
            <br> <!-- Add a line break between log entries for better readability -->
        {% endfor %}
    </ul>
{% else %}
    <p>No search results found.</p>
{% endif %}

</body>
</html>